/// Flutter icons TextIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TextIcons
///      fonts:
///       - asset: fonts/TextIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class TextIcons {
  TextIcons._();

  static const String _kFontFam = 'TextIcons';

  static const IconData account = IconData(0xe903, fontFamily: _kFontFam);
  static const IconData account_group = IconData(0xe920, fontFamily: _kFontFam);
  static const IconData account_group_outline =
      IconData(0xe921, fontFamily: _kFontFam);
  static const IconData account_multiple =
      IconData(0xe92a, fontFamily: _kFontFam);
  static const IconData account_multiple_outline =
      IconData(0xe92e, fontFamily: _kFontFam);
  static const IconData account_outline =
      IconData(0xe935, fontFamily: _kFontFam);
  static const IconData account_supervisor =
      IconData(0xe93f, fontFamily: _kFontFam);
  static const IconData book_open_page_variant =
      IconData(0xeb57, fontFamily: _kFontFam);
  static const IconData book_open_variant =
      IconData(0xeb58, fontFamily: _kFontFam);
  static const IconData format_align_center =
      IconData(0xef87, fontFamily: _kFontFam);
  static const IconData format_align_justify =
      IconData(0xef88, fontFamily: _kFontFam);
  static const IconData format_align_left =
      IconData(0xef89, fontFamily: _kFontFam);
  static const IconData format_align_right =
      IconData(0xef8b, fontFamily: _kFontFam);
  static const IconData format_size = IconData(0xefc3, fontFamily: _kFontFam);
  static const IconData heart = IconData(0xf092, fontFamily: _kFontFam);
  static const IconData heart_broken = IconData(0xf095, fontFamily: _kFontFam);
  static const IconData heart_broken_outline =
      IconData(0xf096, fontFamily: _kFontFam);
  static const IconData heart_multiple =
      IconData(0xf09c, fontFamily: _kFontFam);
  static const IconData heart_multiple_outline =
      IconData(0xf09d, fontFamily: _kFontFam);
  static const IconData heart_outline = IconData(0xf09f, fontFamily: _kFontFam);
  static const IconData information = IconData(0xf119, fontFamily: _kFontFam);
  static const IconData information_outline =
      IconData(0xf11a, fontFamily: _kFontFam);
  static const IconData information_variant =
      IconData(0xf11b, fontFamily: _kFontFam);
  static const IconData lock_reset = IconData(0xf1b0, fontFamily: _kFontFam);
  static const IconData notification_clear_all =
      IconData(0xf291, fontFamily: _kFontFam);
  static const IconData theme_light_dark =
      IconData(0xf602, fontFamily: _kFontFam);
  static const IconData vanish = IconData(0xf699, fontFamily: _kFontFam);
}
